theme: jekyll-theme-cayman
title: Métodos Numéricos con Python - Parte 3 Problemas no lineales, EDOs y EDPs
description: Aprende todos los algoritmos para trabajar con matrices y sistemas para aplicarlos a IA y ML y prográmalo en Python
url: https://www.udemy.com/course/draft/4231882/?referralCode=43D156151FDE49E3186D
link: https://www.udemy.com/course/draft/4231882/?referralCode=43D156151FDE49E3186D
